POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
	"email": "isasdac@email.com",
	"name":"Isaac",
	"password": "isaac123"
}

################

POST http://localhost:3000/auth/sign-in
Content-Type: application/json

{
	"email": "isasdac@email.com",
	"password": "isaac123"
}

################

GET http://localhost:3000/auth/me


